Upgrade packages
svprdga/async_preferences pull request #33
Opened 2024-10-13 08:47 UTC by minhdanh

This should fix #32

2024-10-15 13:42 UTC, svprdga commented
Thank you for your contribution @minhdanh , before proceeding to the PR review, please modify the target branch of this pull request. You should target the `develop` branch. Once modified I will do a full set of tests and I will proceed to create a new version of the plugin.

Thank you.

2024-10-15 13:43 UTC, minhdanh commented
@svprdga Thanks. I've just updated

2024-10-15 13:56 UTC, svprdga requested changes

2024-10-15 13:56 UTC, svprdga commented on pubspec.yaml
You are forcing a specific Dart SDK with these changes. Given that you are not altering any Dart code, the changes in this file should not be required.

2024-10-15 13:56 UTC, svprdga commented on pubspec.lock
As the changes in pubspec.yaml should not be required, changes in this file should also not be required.

2024-10-16 07:01 UTC, minhdanh commented on pubspec.lock
I reverted that changes. Thanks!

2024-10-16 07:01 UTC, minhdanh commented on pubspec.yaml
Reverted

2024-10-16 08:58 UTC, svprdga requested changes
It seems that the example project cannot compile now, I guess that the gradle dependencies should be upgraded as well there.

Please try to fix the example project, maybe by running the AS built-in gradle migration tool is enough.

Thanks.

2024-10-16 12:27 UTC, minhdanh commented
@svprdga I've just fixed the example. Can you please check?

2024-10-16 12:51 UTC, svprdga approved these changes
Thanks for your contribution, I'll create a new release soon with the changes and I'll let you know in the related issue.

2024-10-16 12:52 UTC, merged